import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "@/components/nav";
const inter = Inter({ subsets: ["latin"] });
import { supabase } from "@/lib";
import { auth, currentUser } from "@clerk/nextjs/server";
export const metadata: Metadata = {
  title: "Rubric sync",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Nav userid={userId} />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
